firstjeudy/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2015  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import include, url
from fj.views import liste_villes

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

from django.contrib import admin
from django.contrib.gis import admin as geoadmin

# Pour le robots.txt
from django.http import HttpResponse

admin.autodiscover()


urlpatterns = [
    # Examples:
    # url(r'^$', 'firstjeudy.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # TinyMCE
    url(r'^tinymce/', include('tinymce.urls')),
    # Administration
    url(r'^' + settings.ADMIN_URL +'/', geoadmin.site.urls),

    # Rappel de mot de passe
    url('^' + settings.ADMIN_URL , include('django.contrib.auth.urls')),
    url(
    r'^' + settings.ADMIN_URL +'/password_reset/',
    auth_views.PasswordResetView.as_view(),
    name='admin_password_reset',
    ),
    url(
        r'^' + settings.ADMIN_URL +'/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    url(
        r'^' + settings.ADMIN_URL +'/reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    url(
        r'^' + settings.ADMIN_URL + '/reset/done/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete',
    ),

    # Page d'index  : la liste des villes
    url(r'^$', liste_villes, name='index'),

    # Robots.txt
    url(r'^robots.txt', lambda x: HttpResponse("User-Agent: *\nDisallow:", content_type="text/plain"), name="robots_file"),

    url('^r/', include('ponctu.urls')),

    url('^lieu/', include('lieux.urls')),

    # Flux iCal
    #url(r'^flux$', Flux()),

    url('^', include('fj.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fj/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.urls import path
from fj.views import InscritsDelete, inscription, adl, ical
#from ponctu.views import InscritsDeletePonctu

from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic.base import TemplateView

from django.conf import settings
#from django.conf.urls.static import static

#from django.contrib import admin
#from django.contrib.gis import admin as geoadmin
#admin.autodiscover()

app_name = 'fj'
urlpatterns = [
    # Examples:
    # url(r'^$', 'firstjeudy.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # Page d'index  : la liste des villes
#    url(r'^$', ListeVilles.as_view(), name='index'),
#    url(r'^$', 'fj.views.liste_villes', name='index'),

    # Page de désinscription pour les régulières
    path('del/<str:unique>', InscritsDelete.as_view(), name='inscrit_delete'),

    # Fichier ICAL
    path('<str:code>.ics',
        ical,
        name='ical'
        ),
    #url(r'^(?P<code>.+)/stats$', 'fj.views.stats'),
    # Page pour soumettre à l'Agenda du Libre
    path('agenda/<str:code>',
        adl,
        name='adl'
        ),


    # Page d'une ville : inscription
    path('<str:code>', inscription, name="voir_ville"),

]

fj/models.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2014  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.db import models

# Create your models here.
from lieux.models import Lieu

from tinymce import models as tinymce_models

from django.core.exceptions import ValidationError

from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator

from django.utils.translation import gettext_lazy as _

def pas_de_zero(value):
   if value == 0:
      raise ValidationError(_('Vous ne pouvez pas mettre zéro !'))

def pas_plus_de_cinq(value):
   if value > 5:
      raise ValidationError(_("C'est un peu trop, %s, non ?!") % value)

# Description de la base de données
#

# --- ville

class Ville(models.Model):
    JOURS = (
       (0,_('Dimanche')),
       (1,_('Lundi')),
       (2,_('Mardi')),
       (3,_('Mercredi')),
       (4,_('Jeudi')),
       (5,_('Vendredi')),
       (6,_('Samedi')),
    )
    code = models.CharField(verbose_name=_("Raccourci"), help_text=_("Ce code est utilisé dans les URL. Les caractères autorisés sont des lettres, des chiffres et des tirets (-, _)"), validators=[RegexValidator("^[a-zA-Z0-9_-]*$")], max_length =30, unique=True, null=False)
    nom = models.CharField(verbose_name=_("Nom complet"), max_length=30, unique=True, null=False)
    message = tinymce_models.HTMLField(
            verbose_name=_("Message long"), help_text=_("Apparaît sur la page de la rencontre. Les mots-clés suivants peuvent êtres utilisés :<br>#LIEU_NOM : le nom du lieu<br>#LIEU_URL : l'URL vers la page du lieu<br>#LIEU_ADRESSE : adresse du lieu<br>#HEURE_DEBUT : début de l'évènement<br>#HEURE_FIN : Fin de l'évènement"),
        )
    description = tinymce_models.HTMLField(
        verbose_name=_("Message plus court"), help_text=_("Apparaît sur le résumé.")
        )
    pouet = models.TextField(
            verbose_name=_("Message à envoyer sur Mastodon"),
            default=_("À noter dans vos tablettes :\n#DATE à partir de #HEURE_DEBUT, retrouvez-nous à #LIEU_NOM (#LIEU_ADRESSE). Inscriptiion : #URL.\n##LIEU_VILLE ##LIEU_REGION #Rencontre"),
            help_text=_("Les mots-clés peuvent-être utilisés :<br>#LIEU_NOM : le nom du lieu<br>#LIEU_ADRESSE : l'adresse (courte) du lieu<br>#LIEU_VILLE : la ville de l'évènement<br>#LIEU_REGION : la région de l'évènement<br>#URL : l'URL vers l'évènement<br>#DATE : la date<br>#HEURE_DEBUT : l'heure de début<br>#HEURE_FIN : l'heure de fin"),
            max_length=500,
            null=True)
    lieu = models.ForeignKey(Lieu, null=True, on_delete=models.PROTECT)
    tag = models.CharField(verbose_name=_("Tags"), help_text=_("Utile pour la  soumission à l'Agenda du Libre <br><em>Séparés par des espaces, ils ne peuvent contenir que des lettres minuscules, des chiffres et des tirets. Ajoutez le nom de la ou des organisations de l'événement, mais pas de la ville ou de la région.</em>"), max_length=364, null=True)
    email = models.TextField(
            verbose_name=_("Message sur le courriel de confirmation d'inscription"),
            default=_("Bonjour #PRENOM #NOM.\n\nVotre inscription a bien été prise en compte (pour #NB) :\n- Ville : #VILLE\n- Date : #DATE\n- Cette rencontre aura lieu à #LIEU\n- Adresse IP : #IP\n\nPour annuler votre inscription, vous pouvez cliquer sur le lien suivant : \n#URL_DEL"),
            help_text=_("Les mots-clés suivants peuvent être utilisés :<br>#NOM : Nom de l'inscrit<br>#PRENOM : prénom de l'inscrit<br>#ASSO : Association<br>#VILLE : nom complet de la ville<br>#LIEU : Nom du lieu de la rencontre<br>#URL_LIEU : Lien vers les détails du lieu<br>#DATE : date de la rencontre<br>#HEURE_DEBUT : heure du début de la rencontre<br>#HEURE_FIN : heure de fin de la rencontre<br>#NB : nombre d'inscrit<br>#IP : adresse IP de l'inscrit<br>#URL_ICAL : adresse vers le lien iCalendar<br>#URL_DEL : adresse de désinscription")
            )
    numday = models.IntegerField(verbose_name=_("Jour de la semaine"),null=False, choices=JOURS)
    numweek = models.IntegerField(verbose_name=_("nième semaine du mois"),null=False, validators=[pas_de_zero, pas_plus_de_cinq])
    debut = models.TimeField(verbose_name=_("Heure de début"), null=True, blank=True)
    fin = models.TimeField(verbose_name=_("Heure de fin"), null=True, blank=True)
    limite = models.IntegerField(verbose_name=_("Limite d'inscription"), help_text=_("Nombre d'heure(s) avant le début afin d'alerter le visiteur"), null=True, blank=True)
    autorise_inscription = models.BooleanField(verbose_name=_("Permettre de s'inscrire si la limite est dépassée"), default=True)
    actif = models.BooleanField(verbose_name=_("Actif"), default=True)
    def get_absolute_url(self):
        return "/{0}".format(self.code)
    def __str__ (self):
        return self.nom
    class Meta:
        verbose_name=u"Ville (ou lieu) de l'évènement"
        verbose_name_plural=u"Villes (ou lieux) des évènements"


# -- inscrits

class Inscrits(models.Model):
    unique = models.CharField(verbose_name=_("Numéro unique d'inscription"), max_length=32, unique=True, null=False)
    nom = models.CharField(verbose_name=_("Nom de l'inscrit"), max_length=40, null=False)
    prenom = models.CharField(verbose_name=_("Prénom de l'inscrit"), max_length=40, null=False)
    asso = models.CharField(verbose_name=_("Association"), max_length=150, null=False)
    courriel = models.EmailField(verbose_name=_("Adresse de courriel de l'inscrit"), max_length=40, null=False)
    nb = models.IntegerField(verbose_name=_("Nombre d'inscrits"),validators=[pas_plus_de_cinq], default=1)
    num = models.CharField(verbose_name=_("Numéro du rendez-vous correspondant à la date AAAAMMJJ"), max_length=8, null=False)
    ville = models.ForeignKey('Ville', on_delete=models.PROTECT)
    ip = models.CharField(verbose_name=_("Adresse IP"), max_length=40)

    def __str__ (self):
        return self.nom

    class Meta:
        verbose_name=_("Inscription")
        verbose_name_plural=_("Inscriptions")

fj/forms.py
# -*- coding: utf-8 -*-
#
#  forms.py
#
#  Copyright 2014 Nicolas Grandjean <nicolas@microniko.net>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#
from django import forms
from fj.models import Inscrits
from django.utils.translation import gettext_lazy as _
from random import randint
from django.db.models import Min, Max

from antispam.models import Questions

class InscritsForm(forms.ModelForm):
    """ Formulaire d'inscription """
    boundaries = Questions.objects.aggregate(Min('id'), Max('id'))# Les extrémités
    question = None
    essais = 0
    while question is None:
        try:
            question  = Questions.objects.get(pk=randint(boundaries['id__min'], boundaries['id__max'])) # On en choisie une au hasard
        except Questions.DoesNotExist:
            essais += 1
        else:
            break
    print(essais)
    verification = forms.CharField(required=True,max_length=20, label=question.question)  # Le champ de formulaire avec le libellé de la question
    ident = forms.CharField(initial=str(question.pk), widget=forms.HiddenInput()) # On transmet l'id de la question
    class Meta:
        model = Inscrits
        fields = ('nom', 'prenom', 'asso', 'courriel', 'nb')

    def clean(self):
        cleaned_data = super(InscritsForm, self).clean()
        verif = cleaned_data.get('verification')
        ident = cleaned_data.get('ident')
        reponse = Questions.objects.get(pk=int(ident)).reponse.encode('utf-8')
        if verif:
            verif = cleaned_data.get('verification').encode('utf-8')
    #        print "verif → " + str(verif)
     #       print "ident → "+ str(ident)
      #      print "reponse → " + str(reponse)
            if reponse.upper() != verif.upper():
                raise forms.ValidationError(_("Désolé !"))
        else:
            raise forms.ValidationError(_("Répondez à la question"))

class AgendaForm(forms.Form):
    """ Formulaire de soumission à l'Agenda du Libre """
    email = forms.EmailField(label="Adresse du soumetteur", max_length=100)
    toot = forms.BooleanField(label=_("En profiter pour envoyer un pouet sur Mastodon"),required=False)

fj/templates/agenda.html
{% extends "base.html" %}
{% load i18n %}

{% block header %}
<h1>{{ jour }}
    <sup>{% if perms.fj.change_ville %}<a href="{% url "admin:fj_ville_change" ville.id %}">Modifier</a>{% endif %}
	    {% if user.is_staff %}<a href="{% url 'fj:voir_ville' ville.code  %}">Retour</a> {% endif %}
    </sup>
</h1>
{% endblock %}


{% block content %}

<div id="milieu">



<hr class="separation">

{% if resultatMastodon %}
<p class="infos">{{ resultatMastodon }}
</p>
{% endif %}
{% if resultat %}
<p class="infos">{{ resultat }}
</p>

{% else %}
<form action="" method="post">
{% csrf_token %}
<fieldset>
    <legend>
    {% trans "Soumission à l'Agenda du Libre" %}
    </legend>
    <p>
        {% trans "Le XML ci-dessous sera soumis à l'Agenda du Libre, vous pouvez le modifier si besoin." %}
    </p>
    {% if form %}
    <textarea rows="32" cols="82" id="xml" name="xml">{% include 'adl.xml' %}</textarea>
        {{ form.as_p }}
        <input type="submit" value="Envoyer" />
    {% endif %}
</fieldset>
</form>
{% endif %}


</div>

{% endblock %}

fj/templates/del.html
{% extends "base.html" %}
{% load i18n %}

{% block header %}
<h1>{{ jour }}</h1>

{% endblock %}


{% block content %}

<div id="milieu">


<p class="infos">{% trans "Confirmez-vous la suppression de votre inscription ?" %}</p>

<form method="post" action="">
    {% csrf_token %}
    <input type="submit" value"{% trans "Oui, je ne viens pas" %}" />
    - <a href="{% url "index" %}">{% trans "Si, si je viens !" %}</a>
</form>




</div>


{% endblock %}

fj/templates/stats.html
{% extends "base.html" %}
{% load i18n %}

{% block header %}
<h1>Statistiques</h1>

{% endblock %}

{% block nav %}
<nav id="menu">
    <ul>
        <li><a href="/">Accueil</a></li>
        {% for une_ville in liste_villes %}
        <li{% if une_ville.code = ville.code %} class="actif"{% endif %}>
            <a href='/{{ une_ville.code }}/stats'>{{ une_ville.nom }}</a>
        </li>
        {% endfor %}
    </ul>
</nav>
{% endblock %}




{% block content %}

<div id="milieu">

{{ toto }}

</div>
{% endblock %}

fj/templates/ville.html
{% extends "base.html" %}
{% load leaflet_tags %}
{% load geojson_tags %}
{% load i18n %}

{% block header %}
<h1>{{ jour }}
    <sup>{% if perms.fj.change_ville %}<a href="{% url "admin:fj_ville_change" ville.id %}">Modifier</a>{% endif %}
	    {% if user.is_staff %}<a href="{% url 'fj:adl' ville.code  %}">Envoyer à l'AdL</a> {% endif %}
        <a href="{% url 'fj:ical' ville.code %}">Ajouter à mon agenda</a>
    </sup>
</h1>
{% endblock %}


{% block content %}

<div id="milieu">



{% if ok %} <p class="infos">{% trans "Votre inscription a été prise en compte !" %}<br>
{% trans "Adresse IP" %} : {{ adresse_ip }} {{ v6 }}<br>
<br> {% trans "Pour la supprimer" %} : <a href='{% url "fj:inscrit_delete" unique %}'>{% trans "cliquez-ici" %}</a></p>{% endif %}


<script type="text/javascript">

function map_init_basic (map, options) {
    // On récupère des variables en base
    var position = {{ ville.lieu|geojsonfeature:":champGeo"|safe }};
    var zoom = {{ ville.lieu.zoom|floatformat:0 }};

    // On préparer la carte avec le pointeur
    var layer = L.geoJson(position);
    layer.addTo(map); // La carte est créée

    // On récupère la position du pointeur
    var overlaysBounds=[]; // Sans oublier d'initialiser la variable
    overlaysBounds.push(layer.getBounds());

    // On centre la carte sur la position du pointeur
    map.fitBounds(overlaysBounds, {padding: [50, 50]});

    // On désactive le zoom avec la roulette de la souris
    //map.scrollWheelZoom.disable();

    // Et enfin, on zoom
    map.setZoom(zoom);

}

</script>

{% leaflet_map "map" callback="window.map_init_basic" %}


<p>{{ ville.message|safe }}</p>

<hr class="separation">

{% if ok != True %}
<form action="{{ ville.code }}" method="post">{% csrf_token %}
<fieldset>
    <legend>{% trans "Inscription" %}</legend>
    {% if form %}
    {% if TropTard == True %}<p class="infos">{% trans "Attention, la limite d'inscription est dépassée !" %}<p>{% endif %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer" />
    {% else %}
        {% trans "Les inscriptions sont closes !" %}
    {% endif %}
</fieldset>
</form>
{% endif %}


</div>

<div id="inscrits">
{% trans "Inscrits" %} :
<hr />
<ul>

{% for inscrit in liste_inscrits %}

<li>[{{ inscrit.nb }}] {{inscrit.nom}} {{inscrit.prenom}} (<em>{{inscrit.asso|safe}}</em>) </li>

{% endfor %}
</ul>

<p><strong>
   {% blocktrans count counter=total %}
   {{ total }} inscrit.
   {% plural %}
   {{ total }} inscrits.
   {% endblocktrans %}
</strong></p>

</div>
{% endblock %}