firstjeudy/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2015  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import include, url
from fj.views import liste_villes

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

from django.contrib import admin
from django.contrib.gis import admin as geoadmin

# Pour le robots.txt
from django.http import HttpResponse

admin.autodiscover()


urlpatterns = [
    # Examples:
    # url(r'^$', 'firstjeudy.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # TinyMCE
    url(r'^tinymce/', include('tinymce.urls')),
    # Administration
    url(r'^' + settings.ADMIN_URL +'/', geoadmin.site.urls),

    # Rappel de mot de passe
    url('^' + settings.ADMIN_URL , include('django.contrib.auth.urls')),
    url(
    r'^' + settings.ADMIN_URL +'/password_reset/',
    auth_views.PasswordResetView.as_view(),
    name='admin_password_reset',
    ),
    url(
        r'^' + settings.ADMIN_URL +'/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    url(
        r'^' + settings.ADMIN_URL +'/reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    url(
        r'^' + settings.ADMIN_URL + '/reset/done/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete',
    ),

    # Page d'index  : la liste des villes
    url(r'^$', liste_villes, name='index'),

    # Robots.txt
    url(r'^robots.txt', lambda x: HttpResponse("User-Agent: *\nDisallow:", content_type="text/plain"), name="robots_file"),

    url('^r/', include('ponctu.urls')),

    url('^lieu/', include('lieux.urls')),

    # Flux iCal
    #url(r'^flux$', Flux()),

    url('^', include('fj.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fj/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.urls import path
from fj.views import InscritsDelete, inscription, adl, ical
#from ponctu.views import InscritsDeletePonctu

from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic.base import TemplateView

from django.conf import settings
#from django.conf.urls.static import static

#from django.contrib import admin
#from django.contrib.gis import admin as geoadmin
#admin.autodiscover()

app_name = 'fj'
urlpatterns = [
    # Examples:
    # url(r'^$', 'firstjeudy.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # Page d'index  : la liste des villes
#    url(r'^$', ListeVilles.as_view(), name='index'),
#    url(r'^$', 'fj.views.liste_villes', name='index'),

    # Page de désinscription pour les régulières
    path('del/<str:unique>', InscritsDelete.as_view(), name='inscrit_delete'),

    # Fichier ICAL
    path('<str:code>.ics',
        ical,
        name='ical'
        ),
    #url(r'^(?P<code>.+)/stats$', 'fj.views.stats'),
    # Page pour soumettre à l'Agenda du Libre
    path('agenda/<str:code>',
        adl,
        name='adl'
        ),


    # Page d'une ville : inscription
    path('<str:code>', inscription, name="voir_ville"),

]

ponctu/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.urls import path
from ponctu.views import InscritsDeletePonctu, inscription, adl, ical

from django.conf import settings
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from django.conf.urls.static import static


#from django.contrib import admin
#from django.contrib.gis import admin as geoadmin
#admin.autodiscover()
app_name = 'ponctu'

urlpatterns = [
    # Examples:
    # url(r'^$', 'firstjeudy.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # Page de désinscription pour les ponctuelles
    path('del/<str:unique>', InscritsDeletePonctu.as_view(), name='inscrit_delete_ponctu'),


    # Fichier ICAL
    path('<str:code>.ics',
        ical,
        name='ical'
        ),
    # Page pour soumettre à l'Agenda du Libre
    path('agenda/<str:code>',
        adl,
        name='adl'
        ),
    # Page d'une recontre : inscription
    path('<str:code>', inscription, name="voir_rencontre"),

]

ponctu/models.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2014  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.db import models

# Create your models here.
from lieux.models import Lieu
from django.core.exceptions import ValidationError

from tinymce import models as tinymce_models

from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator

from django.utils.translation import gettext_lazy as _

# Description de la base de données
#

def pas_plus_de_cinq(value):
   if value > 5:
      raise ValidationError(_("C'est un peu trop, %s, non ?!") % value)

# --- Rencontre

class Rencontre(models.Model):
    code = models.CharField(verbose_name=_("Raccourci"), help_text=_("Ce code est utilisé dans les URL. Les caractères autorisés sont des lettres, des chiffres et des tirets (-, _)"), validators=[RegexValidator("^[a-zA-Z0-9_-]*$")], max_length =30, unique=True, null=False)
    nom = models.CharField(verbose_name=_("Nom complet"), max_length=30, unique=True, null=False)
    message = tinymce_models.HTMLField(
        verbose_name=_("Message long"), help_text=_("Apparaît sur la page de la Rencontre. Les mots-clés suivants peuvent êtres utilisés :<br>#LIEU_NOM : le nom du lieu<br>#LIEU_URL : l'URL vers la page du lieu<br>#LIEU_ADRESSE : adresse du lieu<br>#HEURE_DEBUT : début de l'évènement<br>#HEURE_FIN : Fin de l'évènement"),
        )
    description = tinymce_models.HTMLField(
        verbose_name=_("Message plus court"), help_text=("Apparaît sur le résumé."),
        )
    pouet = models.TextField(
            verbose_name=_("Message à envoyer sur Mastodon"),
            default=_("À noter dans vos tablettes :\n#DATE à partir de #HEURE_DEBUT, retrouvez-nous à #LIEU_NOM (#LIEU_ADRESSE). Inscriptiion : #URL.\n##LIEU_VILLE ##LIEU_REGION #Rencontre"),
            help_text=_("Les mots-clés peuvent-être utilisés :<br>#LIEU_NOM : le nom du lieu<br>#LIEU_ADRESSE : l'adresse (courte) du lieu<br>#LIEU_VILLE : la ville de l'évènement<br>#LIEU_REGION : la région de l'évènement<br>#URL : l'URL vers l'évènement<br>#DATE : la date<br>#HEURE_DEBUT : l'heure de début<br>#HEURE_FIN : l'heure de fin"),
            max_length=500,
            null=True)
    email = models.TextField(verbose_name=_("Message sur le courriel de confirmation d'inscription"),default=_("Bonjour #PRENOM #NOM.\n\nVotre inscription (pour #NB) a bien été prise en compte :\n- Rencontre : #RENCONTRE\n- Date : #DATE\n- Lieu : #LIEU\n- Adresse IP : #IP\n\nPour annuler votre inscription, vous pouvez cliquer sur le lien suivant : \n#URL_DEL"), help_text=_("Les mots-clés suivants peuvent être utilisés :<br>#NOM : Nom de l'inscrit<br>#PRENOM : prénom de l'inscrit<br>#ASSO : Association<br>#RENCONTRE : nom complet de la rencontre<br>#DATE : date de la rencontre<br>#HEURE_DEBUT : heure du début de la rencontre<br>#HEURE_FIN : heure de fin de la rencontre<br>#LIEU : Nom du lieu de la rencontre<br>#URL_LIEU : Lien vers les détails du lieu de la rencontre<br>#NB : nombre d'inscrit<br>#IP : adresse IP de l'inscrit<br>#URL_ICAL : adresse vers le lien iCalendar<br>#URL_DEL : adresse de désinscription"))
    lieu = models.ForeignKey(Lieu, null=True, on_delete=models.PROTECT)
    tag = models.CharField(verbose_name=_("Tags"), help_text=_("Utile pour la  soumission à l'Agenda du Libre <br><em>Séparés par des espaces, ils ne peuvent contenir que des lettres minuscules, des chiffres et des tirets. Ajoutez le nom de la ou des organisations de l'événement, mais pas de la ville ou de la région.</em>"), max_length=364, null=True)
    date = models.DateField(verbose_name=_("Date"),help_text=_('Saisissez donc la date !'), null=False)
    debut = models.TimeField(verbose_name=_("Heure de début"), null=True, blank=True)
    fin = models.TimeField(verbose_name=_("Heure de fin"), null=True, blank=True)
    limite = models.IntegerField(verbose_name=_("Limite d'inscription"), help_text=_("Nombre d'heure(s) avant le début afin d'alerter le visiteur"), null=True, blank=True)
    autorise_inscription = models.BooleanField(verbose_name=_("Permettre de s'inscrire si la limite est dépassée"), default=True)
    def get_absolute_url(self):
        return "/r/{0}".format(self.code)
    def __str__ (self):
        return self.nom
    class Meta:
        verbose_name=u"Ville (ou lieu) de l'évènement"
        verbose_name_plural=u"Villes (ou lieux) des évènements"


# -- inscrits

class Inscrits(models.Model):
    unique = models.CharField(verbose_name=_("Numéro unique d'inscription"), max_length=32, unique=True, null=False)
    nom = models.CharField(verbose_name=_("Nom de l'inscrit"), max_length=40, null=False)
    prenom = models.CharField(verbose_name=_("Prénom de l'inscrit"), max_length=40, null=False)
    asso = models.CharField(verbose_name=_("Association"), max_length=150, null=False)
    courriel = models.CharField(verbose_name=_("Adresse de courriel de l'inscrit"), max_length=40, null=False)
    nb = models.IntegerField(verbose_name=_("Nombre d'inscrits"),validators=[pas_plus_de_cinq], default=1)
    rencontre = models.ForeignKey('Rencontre', on_delete=models.PROTECT)
    ip = models.CharField(verbose_name=_("Adresse IP"), max_length=40)

    def __str__ (self):
        return self.nom

    class Meta:
        verbose_name=_("Inscription")
        verbose_name_plural=_("Inscriptions")

ponctu/templates/agenda2.html
{% extends "base.html" %}
{% load i18n %}

{% block header %}
<h1>{{ rencontre.date|date:"l j F Y"|capfirst }}
    <sup>{% if perms.ponctu.change_rencontre %}<a href="{% url "admin:ponctu_rencontre_change" rencontre.id %}">{% trans "Modifier" %}</a>{% endif %}
        {% if user.is_staff %}<a href="{% url 'ponctu:voir_rencontre' rencontre.code  %}">{% trans "Retour" %}</a> {% endif %}
    </sup>
</h1>
{% endblock %}


{% block content %}

<div id="milieu">



<hr class="separation">

{% if resultatMastodon %}
<p class="infos">{{ resultatMastodon }}
</p>
{% endif %}
{% if resultat %}
<p class="infos">{{ resultat }}
</p>
{% else %}
<form action="" method="post">
{% csrf_token %}
<fieldset>
    <legend>
    {% trans "Soumission à l'Agenda du Libre" %}
    </legend>
    <p>
        {% trans "Le XML ci-dessous sera soumis à l'Agenda du Libre, vous pouvez le modifier si besoin." %}
    </p>
    {% if form %}
    <textarea rows="32" cols="82" id="xml" name="xml">{% include 'adl2.xml' %}</textarea>
        {{ form.as_p }}
        <input type="submit" value="{% trans "Envoyer" %}" />
    {% endif %}
</fieldset>
</form>
{% endif %}


</div>

{% endblock %}

ponctu/templates/del.html
{% extends "base.html" %}
{% load i18n %}

{% block header %}
<h1>{{ rencontre.date|date:"l d F Y"|capfirst }}</h1> 

{% endblock %}


{% block content %}

<div id="milieu">


<p class="infos">{% trans "Confirmez-vous la suppression de votre inscription ?" %}</p>

<form method="post" action="">
    {% csrf_token %}
    <input type="submit" value"{% trans "Oui, je ne viens pas" %}" />
    - <a href="{% url "index" %}">{% trans "Si, si je viens !" %}</a>
</form>




</div>


{% endblock %}

ponctu/templates/rencontre.html
{% extends "base.html" %}
{% load leaflet_tags %}
{% load geojson_tags %}
{% load i18n %}

{% block header %}
<h1>{{ rencontre.date|date:"l j F Y"|capfirst }}
    <sup>{% if perms.ponctu.change_rencontre %}<a href="{% url "admin:ponctu_rencontre_change" rencontre.id %}">{% trans "Modifier" %}</a>{% endif %}
        {% if user.is_staff %}<a href="{% url 'ponctu:adl' rencontre.code  %}">{% trans "Envoyer à l'AdL" %}</a> {% endif %}
        <a href="{% url 'ponctu:ical' rencontre.code %}">{% trans "Ajouter à mon agenda" %}</a>
   </sup>
</h1> 
{% endblock %}


{% block content %}

<div id="milieu">



{% if ok %} <p class="infos">{% trans "Votre inscription a été prise en compte !" %}<br>
{% trans "Adresse IP" %} : {{ adresse_ip }} {{ v6 }}<br>
<br> {% trans "Pour la supprimer" %} : <a href='{% url "ponctu:inscrit_delete_ponctu" unique %}'>{% trans "cliquez-ici" %}</a></p>{% endif %}


<script type="text/javascript">

function map_init_basic (map, options) {
    // On récupère des variables en base
    var position = {{ rencontre.lieu|geojsonfeature:":champGeo"|safe }};
    var zoom = {{ rencontre.lieu.zoom|floatformat:0 }};

    // On préparer la carte avec le pointeur
    var layer = L.geoJson(position);
    layer.addTo(map); // La carte est créée

    // On récupère la position du pointeur
    var overlaysBounds=[]; // Sans oublier d'initialiser la variable
    overlaysBounds.push(layer.getBounds());

    // On centre la carte sur la position du pointeur
    map.fitBounds(overlaysBounds, {padding: [50, 50]});

    // On désactive le zoom avec la roulette de la souris
    //map.scrollWheelZoom.disable();

    // Et enfin, on zoom
    map.setZoom(zoom);

}

</script>

{% leaflet_map "map" callback="window.map_init_basic" %}



<p>{{ rencontre.message|safe }}</p>

<hr class="separation">

{% if ok != True %}
<form action="{{ rencontre.code }}" method="post">{% csrf_token %}
<fieldset>
    <legend>{% trans "Inscription" %}</legend>
    {% if form %}
    {% if TropTard == True %}<p class="infos">{% trans "Attention, la limite d'inscription est dépassée !" %}<p>{% endif %}
	    {{ form.as_p }}
	    <input type="submit" value="Envoyer" />
    {% else %}
        {% trans "Les inscriptions sont closes !" %}
    {% endif %}
</fieldset>
</form>
{% endif %}


</div>

<div id="inscrits">
{% trans "Inscrits" %} :
<hr />
<ul>

{% for inscrit in liste_inscrits %}

<li>[{{ inscrit.nb }}] {{inscrit.nom}} {{inscrit.prenom}} (<em>{{inscrit.asso}}</em>) </li>

{% endfor %}
</ul>

<p><strong>
   {% blocktrans count counter=total %}
   {{ total }} inscrit.
   {% plural %}
   {{ total }} inscrits.
   {% endblocktrans %}
</strong></p>

</div>
{% endblock %}